[package]
name = "backup_restore"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22.1"
flate2 = "1.1.2"
serde = { version = "1.0.219", features = ["derive"] }
tokio = { version = "1.45.1", features = ["full"] }
util = { path = "../util" }
