[package]
name = "touch_tone_dialing"
version = "0.1.0"
edition = "2024"

[dependencies]
hound = "3.5.1"
rustfft = "6.4.0"
serde = { version = "1.0.219", features = ["derive"] }
tokio = { version = "1.46.0", features = ["full"] }
util = { path = "../util" }
