[package]
name = "mini_miner"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
sha256 = "1.6.0"
tokio = { version = "1.45.1", features = ["full"] }
util = { path = "../util" }
